### ISSUE TITLE
第二步的时候失败

### ISSUE THREAD

**Issue by wangsitu1** [nondanee/weiboBatchFollow#1]
.

**Comment by nondanee** [comment]
有具体的出错信息吗，截图也行

**Comment by wangsitu1** [comment]
![image](https://user-images.githubusercontent.com/29687605/50329795-b7679280-0533-11e9-88d9-ebcb5d9d23f0.png)
因为昨天微博炸号了心态有点崩， 所以就留了一个没头没尾issue，因为不是计算机专业，所以就死马当活马医按照第一步骤得到了几百个关注的id（那一串数字） 是一个数组 然后我把它填到第二步哪里去了。。。然后运行不起来 （不知道我哪里有问题，还请指教 谢谢啦）

**Comment by nondanee** [comment]
我自己试了下还是可以用的
第二步是进入桌面版的微博 https://www.weibo.com
不是 H5 移动版微博 https://m.weibo.cn
你检查一下，我猜是这个问题

![image](https://user-images.githubusercontent.com/26399680/50333137-45954600-053f-11e9-82bd-7e545ae939c7.png)

P.S. 如果觉得回复 issue 不方便，留其它联系方式也行

**Comment by wangsitu1** [comment]
感谢回复 
用的是进入桌面版的微博 
依然报错
![snipaste_2018-12-21_18-25-47](https://user-images.githubusercontent.com/29687605/50338193-8ea0c680-054e-11e9-9c2e-de855ac8af27.png)
![snipaste_2018-12-21_18-26-25](https://user-images.githubusercontent.com/29687605/50338210-9b251f00-054e-11e9-974b-05e148037544.png)
可能是第一个问题，我google了一下大致意思是说参数列表后面缺少 )
然后假装认真检查了一下语法发现不差括号啊（其实看不懂
搜索到的解决方法[https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Errors/Missing_parenthesis_after_argument_list](url)
方便控制台里面截个图吗（我抄一下作业，对比一下哪里不一样）
![snipaste_2018-12-21_18-35-25](https://user-images.githubusercontent.com/29687605/50338414-33230880-054f-11e9-9203-6076966941dd.png)

**Comment by nondanee** [comment]
进到开发者工具里应该是全屏的，如果有手机那样的框框需要切换到电脑模式，按一下顶上左边第二个
![image](https://user-images.githubusercontent.com/26399680/50339548-eb9e7b80-0552-11e9-92b5-aa120dff727b.png)

这样子的不行
![image](https://user-images.githubusercontent.com/26399680/50339886-b5adc700-0553-11e9-9698-580c88fba213.png)
这样子刷新一次就到手机版了，你可以试一下

你第一次截图里面显示请求全在 m.weibo.cn 上导致 mixed content，感觉还是这个问题

语法没有错就是这样的，那个错误可能是新浪自己的错。（错误信息后面有写来源，但是你没截全...）
栗子：
```javascript
(function(list){
	let index = -1, length = list.length
	function follow(uid){
		let xhr = new XMLHttpRequest()
		xhr.onreadystatechange = function(){
			if(xhr.readyState == 4 && xhr.status == 200){
				let data = JSON.parse(xhr.responseText)
				if(data.code == 100000)
					console.log(`${index + 1}/${length}`, uid, data.data.fnick, '关注成功')
				else if(data.code == 100001)
					console.log(`${index + 1}/${length}`, uid, '关注失败')
			}
		}
		xhr.open('POST', `https://www.weibo.com/aj/f/followed?ajwvr=6&__rnd=${Date.now()}`)
		xhr.setRequestHeader('Content-type', 'application/x-www-form-urlencoded')
		xhr.send(`uid=${uid}&objectid=&f=1&extra=&refer_sort=&refer_flag=1005050001_&location=page_100505_home&oid=${uid}&wforce=1&nogroup=false&fnick=&refer_lflag=&refer_from=profile_headerv6&_t=0`)
	}
	let scheduled = setInterval(function(){
		index += 1
		follow(list[index])
	}, 2000)
	setTimeout(function(){
		clearTimeout(scheduled)
	}, 2000 * length)
})([5173636286,5546145590,1784372732,6870880303,6240904483,6785549332,5617046421,3787649505,6607671219,5578350522,1850988623,1649614847,1975435933,3109080617,5743923782,2715025067,3139784387,6054450374,6426685949,2292568710,1686852537,6314479522,6064312916,5873553708,1876944985,3235996844,2925898895,6625446221,5470052433,1895431523,5574731817,5995542004,5031163331,5664670417,1727681013,1794624133,1580686265,6266263452,2580164085,6502577538,1379264823])
```

**Comment by wangsitu1** [comment]
好了 好了成功了 谢谢啦！: )

**Comment by nondanee** [comment]
👌
