### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by luckylele666** [nondanee/weiboBatchFollow#10]
按照描述把第一步代码复制进 console 等了一会儿「出错了」，是我操作问题，还是该方法已经失效了呢？
麻烦解答一下。

**Comment by nondanee** [comment]
试了下没问题
"出错了"后面的 error message 是什么？

**Comment by luckylele666** [comment]
出错了 (Cannot read property 'msg' of undefined) 下面是 uid（应该是导出了一部分）

e.<computed> | @ | vendor.a78904f6.js:1
-- | -- | --
  | (anonymous) | @ | VM44:16
  | Promise.catch (async) |   |  
  | (anonymous) | @ | VM44:16
  | (anonymous) | @ | VM44:17
--- --- --- --- --- --- --- --- --- --- --- 
成功导出的那部分是填在const follow = **uid** => 「uid」里吗？

**Comment by nondanee** [comment]
额，感觉是被接口 425 punish 了

不是，填在最后一行就行

```diff
- })(/*上一步的结果*/)
+ })([123,456,789])
```
