### ISSUE TITLE
关注列表中存在无法关注的账号则停止

### ISSUE THREAD

**Issue by idrawer** [nondanee/weiboBatchFollow#12]
会报错：
`出错了 (captcha is required)
以下 ID 还未处理，请之后再试`
剩下的账号则无法继续运行关注。希望提供解决

**Comment by nondanee** [comment]
等个十几分钟几十分钟再试

**Comment by nondanee** [comment]
抱歉
微博每日关注人数有上限，到达上限以后要输验证码的
