### ISSUE TITLE
blocked by CORS policy

### ISSUE THREAD

**Issue by U97F3** [nondanee/weiboBatchFollow#16]
Access to XMLHttpRequest at 'https://m.weibo.cn/aj/log/userdevice?ajwvr=6?ajwvr=6&jumpfrom=weibocom&ajwvr=6' (redirected from 'https://weibo.com/aj/log/userdevice?ajwvr=6') from origin 'https://weibo.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
lib.js?version=1d4d6f29bffd04a5:1 GET https://m.weibo.cn/aj/log/userdevice?ajwvr=6?ajwvr=6&jumpfrom=weibocom&ajwvr=6 net::ERR_FAILED
home?wvr=5&sudaref=passport.weibo.com:1 Access to XMLHttpRequest at 'https://m.weibo.cn/aj/log/userdevice?ajwvr=6?ajwvr=6&jumpfrom=weibocom&ajwvr=6' (redirected from 'https://weibo.com/aj/log/userdevice?ajwvr=6') from origin 'https://weibo.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
lib.js?version=1d4d6f29bffd04a5:1 GET https://m.weibo.cn/aj/log/userdevice?ajwvr=6?ajwvr=6&jumpfrom=weibocom&ajwvr=6 net::ERR_FAILED

一直提示GET这个URL Failed，什么情况

**Comment by nondanee** [comment]
README 中有说明
关注要到 PC 版微博 www.weibo.com 操作
不要在 H5 版操作
