### ISSUE TITLE
批量关注200个之后无法关注了

### ISSUE THREAD

**Issue by FakeGeek92** [nondanee/weiboBatchFollow#2]
出现了这个错误。Access to XMLHttpRequest at 'https://www.weibo.com/aj/f/followed?ajwvr=6&__rnd=1547022792636' from origin 'https://weibo.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
home:1

**Comment by nondanee** [comment]
不好意思没有大量测试过
可能是新浪的机器人审查
可以的话麻烦提供一下 network 的信息
建议等一段时间再试

**Comment by FakeGeek92** [comment]
额，不用和我不好意思，毕竟我才是伸手党...
隔了一天试了还是不行..
我录了个视频，有空的话可以看看。如果有必要，可以加我 wx：fake**geek（去掉星号）
https://d.pr/v/VFQllP

**Comment by nondanee** [comment]
我看了下好像是登录掉了？
![image](https://user-images.githubusercontent.com/26399680/51046705-c3f67c80-1601-11e9-82bc-84674fe8bfa5.png)
关注的请求被重定向到 passport.weibo.com 上了，这个是微博登录的入口。
看看直接在网页上随便点一个关注会有什么提示吗？

**Comment by nondanee** [comment]
结论：在网页上手动关注任一用户，再运行脚本就可以了
十分感谢 @FakeGeek92 发现问题并配合 debug
