### ISSUE TITLE
返回的关注列表为空

### ISSUE THREAD

**Issue by winfet** [nondanee/weiboBatchFollow#3]
![image](https://user-images.githubusercontent.com/14037835/55895763-6ae1b900-5bef-11e9-8d36-9f773c55cef6.png)

**Comment by nondanee** [comment]
无法复现，麻烦贴一下开发者工具里 network 的截图，应该有很多 getSecond 的请求

![image](https://user-images.githubusercontent.com/26399680/56074273-d1c6c400-5de1-11e9-8824-1cf3fa4f24aa.png)

如果是因为 '这里还没有内容' 的问题 break 了，那是微博 API 的问题，在 H5 版微博里看自己的关注应该也会没有数据
