### ISSUE TITLE
最近被炸号了  第二步一直显示这个 小白麻烦了

### ISSUE THREAD

**Issue by XavierHui** [nondanee/weiboBatchFollow#6]
![图片20200303173202](https://user-images.githubusercontent.com/10363308/75762211-43e72500-5d75-11ea-9968-fe0ed889c5c1.jpg)
![图片20200303173503](https://user-images.githubusercontent.com/10363308/75762266-595c4f00-5d75-11ea-9bc3-163e6a8f7710.jpg)

**Comment by nondanee** [comment]
第二步第 1 点
> 1. 前往 PC 版首页 (www.weibo.com)

你这个还是微博 H5 版 (m.weibo.cn)

**Comment by XavierHui** [comment]
第二步可能是我点了这里 取消了就好了 
![图片20200304105941](https://user-images.githubusercontent.com/10363308/75841019-ac7ee200-5e07-11ea-9bc2-d503ce245f87.jpg)

但是现在又提示这个了 
![图片20200304105515](https://user-images.githubusercontent.com/10363308/75841046-bef91b80-5e07-11ea-96b1-deda7d08ff83.jpg)

感谢

**Comment by nondanee** [comment]
界面上随便找一个账号关注一下看看
