### ISSUE TITLE
如何修改去获取明星的全部关注列表

### ISSUE THREAD

**Issue by barnett2010** [nondanee/weiboBatchFollow#7]
我尝试改uid好像没有用，没有结果

**Comment by nondanee** [comment]
我看了下直接改 uid 就可以
不可能没有结果的，成功或者失败都会有提示
应该是量大还没执行完，去 network 里看看是不是还在请求

**Comment by barnett2010** [comment]
> 我看了下直接改 uid 就可以
> 不可能没有结果的，成功或者失败都会有提示
> 应该是量大还没执行完，去 network 里看看是不是还在请求

感谢大佬回复
我只修改了这句
const {uid} = 十位数

然后回车，，立马就出了这样一个结果

 获取完成

[]
e.(anonymous function) @ vendor.0867674d.js:1
polling.catch.error @ VM280:16
Promise.catch (async)
(anonymous) @ VM280:16
(anonymous) @ VM280:17


并没有看到一串uid结果

**Comment by nondanee** [comment]
> const {uid} = 十位数

这个是语法错误，所以直接抛异常
正确的是：const uid = 十位数

**Comment by barnett2010** [comment]
有结果了，再次感谢大佬
