### ISSUE TITLE
第二步错误求助大佬

### ISSUE THREAD

**Issue by Ariellixn** [nondanee/weiboBatchFollow#9]
![360截图20200321195609083](https://user-images.githubusercontent.com/62467443/77225849-1dffb400-6bae-11ea-9206-e2eba946ac9f.jpg)
![360截图20200321195706845](https://user-images.githubusercontent.com/62467443/77225850-1f30e100-6bae-11ea-8f72-3131c95dbf47.jpg)
![360截图20200321195648926](https://user-images.githubusercontent.com/62467443/77225853-20620e00-6bae-11ea-8e6f-bec23159a964.jpg)

**Comment by nondanee** [comment]
emmm 填错位置了，参考 👉  https://github.com/nondanee/weiboBatchFollow/issues/8#issuecomment-599033716

**Comment by Ariellixn** [comment]
成功了谢谢！就是每次只能关注31个 我之前这些问题都看了但是没反应过来lol 再次感谢！

**Comment by nondanee** [comment]
好的👌，31 个应该是微博的限制
